In [30]:
import polars as pl

In [31]:
master = pl.read_csv("Store39_Dataset/MasterDataset.csv", try_parse_dates=True)
master.head()

shape: (5, 14)
┌────────────┬──────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ date       ┆ item_nbr ┆ unit_sale ┆ onpromoti ┆ … ┆ is_Nation ┆ is_Local ┆ is_likely ┆ oil_price │
│ ---        ┆ ---      ┆ s         ┆ on        ┆   ┆ al        ┆ ---      ┆ _closed   ┆ ---       │
│ date       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ i64      ┆ ---       ┆ f64       │
│            ┆          ┆ f64       ┆ i64       ┆   ┆ i64       ┆          ┆ i64       ┆           │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 2016-06-01 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ 0         ┆ 0        ┆ 0         ┆ 49.07     │
│ 2016-06-02 ┆ 103501   ┆ 8.0       ┆ 0         ┆ … ┆ 0         ┆ 0        ┆ 0         ┆ 49.14     │
│ 2016-06-03 ┆ 103501   ┆ 10.0      ┆ 0         ┆ … ┆ 0         ┆ 0        ┆ 0         ┆ 48.69     │
│ 2016-06-04 ┆ 103501   ┆ 14.0      ┆ 0         ┆ … ┆ 0         ┆ 0        ┆ 0         ┆ 48.69     │
│ 2016-06-05 ┆ 103501   ┆ 11.0      ┆ 0         ┆ … ┆ 0         ┆ 0        ┆ 0         ┆ 48.69     │
└────────────┴──────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [32]:
master = master.with_columns(
    [
        pl.col('unit_sales').log1p(),
        pl.col('transactions').log1p()
    ]
)

In [33]:
master = master.with_columns([
    pl.col("date").dt.weekday().cast(pl.Int8).alias("day_of_week"),
    (pl.col("date").dt.weekday() >= 5).cast(pl.Int8).alias("is_weekend"),
    (pl.col("date").dt.day() <= 3).cast(pl.Int8).alias("is_month_start"),
    (pl.col("date").dt.day() >= 28).cast(pl.Int8).alias("is_month_end")
])
master.head()

shape: (5, 18)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date      ┆ item_nbr ┆ unit_sale ┆ onpromoti ┆ … ┆ day_of_we ┆ is_weeken ┆ is_month_ ┆ is_month_ │
│ ---       ┆ ---      ┆ s         ┆ on        ┆   ┆ ek        ┆ d         ┆ start     ┆ end       │
│ date      ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆ f64       ┆ i64       ┆   ┆ i8        ┆ i8        ┆ i8        ┆ i8        │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2016-06-0 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ 3         ┆ 0         ┆ 1         ┆ 0         │
│ 1         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.197225  ┆ 0         ┆ … ┆ 4         ┆ 0         ┆ 1         ┆ 0         │
│ 2         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.397895  ┆ 0         ┆ … ┆ 5         ┆ 1         ┆ 1         ┆ 0         │
│ 3         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.70805   ┆ 0         ┆ … ┆ 6         ┆ 1         ┆ 0         ┆ 0         │
│ 4         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.484907  ┆ 0         ┆ … ┆ 7         ┆ 1         ┆ 0         ┆ 0         │
│ 5         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [34]:
family_sales = master.select(["date", "unit_sales", "family"])
family_sales.head()

shape: (5, 3)
┌────────────┬────────────┬──────────┐
│ date       ┆ unit_sales ┆ family   │
│ ---        ┆ ---        ┆ ---      │
│ date       ┆ f64        ┆ str      │
╞════════════╪════════════╪══════════╡
│ 2016-06-01 ┆ 0.0        ┆ CLEANING │
│ 2016-06-02 ┆ 2.197225   ┆ CLEANING │
│ 2016-06-03 ┆ 2.397895   ┆ CLEANING │
│ 2016-06-04 ┆ 2.70805    ┆ CLEANING │
│ 2016-06-05 ┆ 2.484907   ┆ CLEANING │
└────────────┴────────────┴──────────┘

In [35]:
family_sales = family_sales.group_by(["family", "date"]).agg(pl.col("unit_sales").sum()).sort(by=["family", "date"])
family_sales.head()

shape: (5, 3)
┌────────────┬────────────┬────────────┐
│ family     ┆ date       ┆ unit_sales │
│ ---        ┆ ---        ┆ ---        │
│ str        ┆ date       ┆ f64        │
╞════════════╪════════════╪════════════╡
│ AUTOMOTIVE ┆ 2016-06-01 ┆ 0.0        │
│ AUTOMOTIVE ┆ 2016-06-02 ┆ 5.375278   │
│ AUTOMOTIVE ┆ 2016-06-03 ┆ 3.465736   │
│ AUTOMOTIVE ┆ 2016-06-04 ┆ 3.688879   │
│ AUTOMOTIVE ┆ 2016-06-05 ┆ 7.860185   │
└────────────┴────────────┴────────────┘

In [36]:
family_sales = family_sales.with_columns(
    (pl.col("unit_sales").cum_sum() / pl.col("unit_sales").cum_count()).over("family").alias("family_mean_sales")
)
family_sales = family_sales.drop("unit_sales")
family_sales.head()

shape: (5, 3)
┌────────────┬────────────┬───────────────────┐
│ family     ┆ date       ┆ family_mean_sales │
│ ---        ┆ ---        ┆ ---               │
│ str        ┆ date       ┆ f64               │
╞════════════╪════════════╪═══════════════════╡
│ AUTOMOTIVE ┆ 2016-06-01 ┆ 0.0               │
│ AUTOMOTIVE ┆ 2016-06-02 ┆ 2.687639          │
│ AUTOMOTIVE ┆ 2016-06-03 ┆ 2.947005          │
│ AUTOMOTIVE ┆ 2016-06-04 ┆ 3.132473          │
│ AUTOMOTIVE ┆ 2016-06-05 ┆ 4.078016          │
└────────────┴────────────┴───────────────────┘

In [37]:
master = master.with_columns([
    (pl.col("unit_sales").cum_sum()/pl.col("unit_sales").cum_count()).over("item_nbr").alias("item_mean_sales"),
    pl.col("unit_sales").cumulative_eval(pl.element().std(ddof=0)).over("item_nbr").alias("item_std_sales")
])

master = master.join(family_sales, on=["family", "date"], how="left")

master = master.with_columns(
    (pl.col("item_mean_sales") / pl.col("family_mean_sales").clip(lower_bound=0.01)).alias("sales_vs_family_mean")
)

master = master.drop("family_mean_sales")

master.head()

shape: (5, 21)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date      ┆ item_nbr ┆ unit_sale ┆ onpromoti ┆ … ┆ is_month_ ┆ item_mean ┆ item_std_ ┆ sales_vs_ │
│ ---       ┆ ---      ┆ s         ┆ on        ┆   ┆ end       ┆ _sales    ┆ sales     ┆ family_me │
│ date      ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ an        │
│           ┆          ┆ f64       ┆ i64       ┆   ┆ i8        ┆ f64       ┆ f64       ┆ ---       │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2016-06-0 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 1         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.197225  ┆ 0         ┆ … ┆ 0         ┆ 1.098612  ┆ 1.098612  ┆ 0.005808  │
│ 2         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.397895  ┆ 0         ┆ … ┆ 0         ┆ 1.531707  ┆ 1.086174  ┆ 0.005793  │
│ 3         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.70805   ┆ 0         ┆ … ┆ 0         ┆ 1.825793  ┆ 1.069715  ┆ 0.005652  │
│ 4         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.484907  ┆ 0         ┆ … ┆ 0         ┆ 1.957615  ┆ 0.992442  ┆ 0.005491  │
│ 5         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [38]:
master = master.with_columns([
    pl.col("unit_sales").shift(0).over("item_nbr").alias("lag_1"),
    pl.col("unit_sales").shift(2).over("item_nbr").alias("lag_3"),
    pl.col("unit_sales").shift(4).over("item_nbr").alias("lag_5"),
    pl.col("unit_sales").shift(6).over("item_nbr").alias("lag_7"),
    pl.col("unit_sales").shift(13).over("item_nbr").alias("lag_14"),
    pl.col("unit_sales").shift(29).over("item_nbr").alias("lag_30"),
    pl.col("unit_sales").shift(59).over("item_nbr").alias("lag_60"),
    pl.col("unit_sales").shift(139).over("item_nbr").alias("lag_140")
])
master.head()

shape: (5, 29)
┌────────────┬──────────┬────────────┬─────────────┬───┬────────┬────────┬────────┬─────────┐
│ date       ┆ item_nbr ┆ unit_sales ┆ onpromotion ┆ … ┆ lag_14 ┆ lag_30 ┆ lag_60 ┆ lag_140 │
│ ---        ┆ ---      ┆ ---        ┆ ---         ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---     │
│ date       ┆ i64      ┆ f64        ┆ i64         ┆   ┆ f64    ┆ f64    ┆ f64    ┆ f64     │
╞════════════╪══════════╪════════════╪═════════════╪═══╪════════╪════════╪════════╪═════════╡
│ 2016-06-01 ┆ 103501   ┆ 0.0        ┆ 0           ┆ … ┆ null   ┆ null   ┆ null   ┆ null    │
│ 2016-06-02 ┆ 103501   ┆ 2.197225   ┆ 0           ┆ … ┆ null   ┆ null   ┆ null   ┆ null    │
│ 2016-06-03 ┆ 103501   ┆ 2.397895   ┆ 0           ┆ … ┆ null   ┆ null   ┆ null   ┆ null    │
│ 2016-06-04 ┆ 103501   ┆ 2.70805    ┆ 0           ┆ … ┆ null   ┆ null   ┆ null   ┆ null    │
│ 2016-06-05 ┆ 103501   ┆ 2.484907   ┆ 0           ┆ … ┆ null   ┆ null   ┆ null   ┆ null    │
└────────────┴──────────┴────────────┴─────────────┴───┴────────┴────────┴────────┴─────────┘

In [39]:
master = master.with_columns([
    pl.col("unit_sales").rolling_mean(3).over("item_nbr").alias("rolling_mean_3"),
    pl.col("unit_sales").rolling_mean(7).over("item_nbr").alias("rolling_mean_7"),
    pl.col("unit_sales").rolling_mean(14).over("item_nbr").alias("rolling_mean_14"),
    pl.col("unit_sales").rolling_mean(30).over("item_nbr").alias("rolling_mean_30"),
    pl.col("unit_sales").rolling_mean(140).over("item_nbr").alias("rolling_mean_140"),
    pl.col("unit_sales").rolling_std(7).over("item_nbr").alias("rolling_std_7"),
    pl.col("unit_sales").rolling_std(14).over("item_nbr").alias("rolling_std_14"),
    pl.col("unit_sales").rolling_std(30).over("item_nbr").alias("rolling_std_30"),
    pl.col("unit_sales").rolling_max(7).over("item_nbr").alias("rolling_max_7"),
    pl.col("unit_sales").rolling_min(7).over("item_nbr").alias("rolling_min_7")
])
master.head(10)

shape: (10, 39)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date      ┆ item_nbr ┆ unit_sale ┆ onpromoti ┆ … ┆ rolling_s ┆ rolling_s ┆ rolling_m ┆ rolling_m │
│ ---       ┆ ---      ┆ s         ┆ on        ┆   ┆ td_14     ┆ td_30     ┆ ax_7      ┆ in_7      │
│ date      ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆ f64       ┆ i64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2016-06-0 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.197225  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.397895  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 3         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.70805   ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 4         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.484907  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 5         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 1.609438  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.197225  ┆ 0         ┆ … ┆ null      ┆ null      ┆ 2.70805   ┆ 0.0       │
│ 7         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ null      ┆ null      ┆ 2.70805   ┆ 0.0       │
│ 8         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 1.791759  ┆ 0         ┆ … ┆ null      ┆ null      ┆ 2.70805   ┆ 0.0       │
│ 9         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-1 ┆ 103501   ┆ 1.098612  ┆ 0         ┆ … ┆ null      ┆ null      ┆ 2.70805   ┆ 0.0       │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [40]:
master = master.with_columns([
    pl.col("transactions").shift(0).over("item_nbr").alias("transactions_lag_1"),
    pl.col("transactions").shift(2).over("item_nbr").alias("transactions_lag_3"),
    pl.col("transactions").shift(6).over("item_nbr").alias("transactions_lag_7"),
    pl.col("transactions").shift(13).over("item_nbr").alias("transactions_lag_14"),
    pl.col("transactions").rolling_mean(7).over("item_nbr").alias("transactions_rolling_7"),
    pl.col("transactions").rolling_mean(14).over("item_nbr").alias("transactions_rolling_14"),
    pl.col("transactions").rolling_mean(30).over("item_nbr").alias("transactions_rolling_30")
]).with_columns(
    (pl.col("transactions_lag_1")/pl.col("transactions_rolling_30")).clip(lower_bound=0.5).alias("traffic_ratio")
)
master.head(10)

shape: (10, 47)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date      ┆ item_nbr ┆ unit_sale ┆ onpromoti ┆ … ┆ transacti ┆ transacti ┆ transacti ┆ traffic_r │
│ ---       ┆ ---      ┆ s         ┆ on        ┆   ┆ ons_rolli ┆ ons_rolli ┆ ons_rolli ┆ atio      │
│ date      ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ng_7      ┆ ng_14     ┆ ng_30     ┆ ---       │
│           ┆          ┆ f64       ┆ i64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│           ┆          ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2016-06-0 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.197225  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.397895  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 3         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.70805   ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 4         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.484907  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 5         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 1.609438  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.197225  ┆ 0         ┆ … ┆ 6.239439  ┆ null      ┆ null      ┆ null      │
│ 7         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ 7.263962  ┆ null      ┆ null      ┆ null      │
│ 8         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 1.791759  ┆ 0         ┆ … ┆ 7.261041  ┆ null      ┆ null      ┆ null      │
│ 9         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-1 ┆ 103501   ┆ 1.098612  ┆ 0         ┆ … ┆ 7.264786  ┆ null      ┆ null      ┆ null      │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [41]:
master = master.with_columns([
    pl.col("oil_price").shift(0).over("item_nbr").alias("oil_price_lag_1"),
    pl.col("oil_price").shift(2).over("item_nbr").alias("oil_price_lag_3"),
    pl.col("oil_price").shift(6).over("item_nbr").alias("oil_price_lag_7"),
    pl.col("oil_price").rolling_mean(7).over("item_nbr").alias("oil_price_rolling_mean_7"),
    pl.col("oil_price").rolling_mean(30).over("item_nbr").alias("oil_price_rolling_mean_30")
]).with_columns(
    ((pl.col("oil_price_lag_1") - pl.col("oil_price_lag_7")) / pl.col("oil_price_lag_7")).alias("oil_price_change_7")
)
master.head(10)

shape: (10, 53)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date      ┆ item_nbr ┆ unit_sale ┆ onpromoti ┆ … ┆ oil_price ┆ oil_price ┆ oil_price ┆ oil_price │
│ ---       ┆ ---      ┆ s         ┆ on        ┆   ┆ _lag_7    ┆ _rolling_ ┆ _rolling_ ┆ _change_7 │
│ date      ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ mean_7    ┆ mean_30   ┆ ---       │
│           ┆          ┆ f64       ┆ i64       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ f64       │
│           ┆          ┆           ┆           ┆   ┆           ┆ f64       ┆ f64       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2016-06-0 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.197225  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.397895  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 3         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.70805   ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 4         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.484907  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 5         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 1.609438  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.197225  ┆ 0         ┆ … ┆ 49.07     ┆ 49.194286 ┆ null      ┆ 0.026493  │
│ 7         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ 49.14     ┆ 49.502857 ┆ null      ┆ 0.042532  │
│ 8         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 1.791759  ┆ 0         ┆ … ┆ 48.69     ┆ 49.7      ┆ null      ┆ 0.037585  │
│ 9         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-1 ┆ 103501   ┆ 1.098612  ┆ 0         ┆ … ┆ 48.69     ┆ 49.757143 ┆ null      ┆ 0.008215  │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [42]:
master = master.with_columns([
    pl.col("onpromotion").shift(0).over("item_nbr").alias("promo_lag_1"),
    pl.col("onpromotion").shift(2).over("item_nbr").alias("promo_lag_3"),
    pl.col("onpromotion").shift(6).over("item_nbr").alias("promo_lag_7"),
    pl.col("onpromotion").cast(pl.Int8).rolling_sum(7).over("item_nbr").alias("promo_count_7"),
    pl.col("onpromotion").cast(pl.Int8).rolling_sum(30).over("item_nbr").alias("promo_count_30")
])
master = master.with_columns(
    pl.when(pl.col("onpromotion").over("item_nbr") == 1)
    .then(pl.col("date"))
    .otherwise(None)
    .forward_fill()
    .over("item_nbr")
    .alias("last_promo_date")
).with_columns(
    (pl.col("date") - pl.col("last_promo_date"))
    .dt.total_days()
    .fill_null(999)
    .alias("days_since_last_promo")
).drop("last_promo_date")

master.head(10)

shape: (10, 59)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date      ┆ item_nbr ┆ unit_sale ┆ onpromoti ┆ … ┆ promo_lag ┆ promo_cou ┆ promo_cou ┆ days_sinc │
│ ---       ┆ ---      ┆ s         ┆ on        ┆   ┆ _7        ┆ nt_7      ┆ nt_30     ┆ e_last_pr │
│ date      ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ omo       │
│           ┆          ┆ f64       ┆ i64       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ ---       │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2016-06-0 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 999       │
│ 1         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.197225  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 0         │
│ 2         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.397895  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 0         │
│ 3         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.70805   ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 0         │
│ 4         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.484907  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 0         │
│ 5         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 1.609438  ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 999       │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.197225  ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ null      ┆ 0         │
│ 7         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ null      ┆ 0         │
│ 8         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 1.791759  ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ null      ┆ 0         │
│ 9         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-1 ┆ 103501   ┆ 1.098612  ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ null      ┆ 0         │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [43]:
holidays = pl.read_csv("Store39_Dataset/holidays.csv", try_parse_dates=True)

holiday_dates = (
    holidays.filter(pl.col("is_Holiday") == 1).select("date").sort("date")["date"].to_list()
)

unique_dates = master["date"].unique().sort().to_list()

days_since = []
days_to = []

for d in unique_dates:
    past = [h for h in holiday_dates if h < d]
    days_since.append((d - past[-1]).days if past else 999)

    future = [h for h in holiday_dates if h > d]
    days_to.append((future[0] - d).days if future else 999)

holiday_distances = pl.DataFrame({
    "date": unique_dates,
    "days_since_last_holiday": days_since,
    "days_to_next_holiday": days_to,
})
holiday_distances.head()

shape: (5, 3)
┌────────────┬─────────────────────────┬──────────────────────┐
│ date       ┆ days_since_last_holiday ┆ days_to_next_holiday │
│ ---        ┆ ---                     ┆ ---                  │
│ date       ┆ i64                     ┆ i64                  │
╞════════════╪═════════════════════════╪══════════════════════╡
│ 2016-06-01 ┆ 999                     ┆ 130                  │
│ 2016-06-02 ┆ 999                     ┆ 129                  │
│ 2016-06-03 ┆ 999                     ┆ 128                  │
│ 2016-06-04 ┆ 999                     ┆ 127                  │
│ 2016-06-05 ┆ 999                     ┆ 126                  │
└────────────┴─────────────────────────┴──────────────────────┘

In [44]:
master = master.join(holiday_distances, on="date", how="left")
master.head()

shape: (5, 61)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date      ┆ item_nbr ┆ unit_sale ┆ onpromoti ┆ … ┆ promo_cou ┆ days_sinc ┆ days_sinc ┆ days_to_n │
│ ---       ┆ ---      ┆ s         ┆ on        ┆   ┆ nt_30     ┆ e_last_pr ┆ e_last_ho ┆ ext_holid │
│ date      ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ omo       ┆ liday     ┆ ay        │
│           ┆          ┆ f64       ┆ i64       ┆   ┆ i64       ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆           ┆           ┆   ┆           ┆ i64       ┆ i64       ┆ i64       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2016-06-0 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ null      ┆ 999       ┆ 999       ┆ 130       │
│ 1         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.197225  ┆ 0         ┆ … ┆ null      ┆ 0         ┆ 999       ┆ 129       │
│ 2         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.397895  ┆ 0         ┆ … ┆ null      ┆ 0         ┆ 999       ┆ 128       │
│ 3         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.70805   ┆ 0         ┆ … ┆ null      ┆ 0         ┆ 999       ┆ 127       │
│ 4         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-06-0 ┆ 103501   ┆ 2.484907  ┆ 0         ┆ … ┆ null      ┆ 0         ┆ 999       ┆ 126       │
│ 5         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [45]:
master = master.drop_nulls(subset=[
    "rolling_mean_140"
])
master.null_count()
master.head(10)

shape: (10, 61)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date      ┆ item_nbr ┆ unit_sale ┆ onpromoti ┆ … ┆ promo_cou ┆ days_sinc ┆ days_sinc ┆ days_to_n │
│ ---       ┆ ---      ┆ s         ┆ on        ┆   ┆ nt_30     ┆ e_last_pr ┆ e_last_ho ┆ ext_holid │
│ date      ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ omo       ┆ liday     ┆ ay        │
│           ┆          ┆ f64       ┆ i64       ┆   ┆ i64       ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆           ┆           ┆   ┆           ┆ i64       ┆ i64       ┆ i64       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2016-10-1 ┆ 103501   ┆ 1.386294  ┆ 1         ┆ … ┆ 8         ┆ 0         ┆ 9         ┆ 15        │
│ 8         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-10-1 ┆ 103501   ┆ 1.609438  ┆ 1         ┆ … ┆ 9         ┆ 0         ┆ 10        ┆ 14        │
│ 9         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-10-2 ┆ 103501   ┆ 1.098612  ┆ 1         ┆ … ┆ 10        ┆ 999       ┆ 11        ┆ 13        │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-10-2 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ 10        ┆ 999       ┆ 12        ┆ 12        │
│ 1         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-10-2 ┆ 103501   ┆ 2.484907  ┆ 1         ┆ … ┆ 11        ┆ 999       ┆ 13        ┆ 11        │
│ 2         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-10-2 ┆ 103501   ┆ 1.609438  ┆ 1         ┆ … ┆ 12        ┆ 999       ┆ 14        ┆ 10        │
│ 3         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-10-2 ┆ 103501   ┆ 1.386294  ┆ 1         ┆ … ┆ 13        ┆ 999       ┆ 15        ┆ 9         │
│ 4         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-10-2 ┆ 103501   ┆ 1.098612  ┆ 1         ┆ … ┆ 14        ┆ 999       ┆ 16        ┆ 8         │
│ 5         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-10-2 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ 14        ┆ 999       ┆ 17        ┆ 7         │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2016-10-2 ┆ 103501   ┆ 0.0       ┆ 0         ┆ … ┆ 14        ┆ 999       ┆ 18        ┆ 6         │
│ 7         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [46]:
master.null_count()

shape: (1, 61)
┌──────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ date ┆ item_nbr ┆ unit_sales ┆ onpromotio ┆ … ┆ promo_coun ┆ days_since ┆ days_since ┆ days_to_n │
│ ---  ┆ ---      ┆ ---        ┆ n          ┆   ┆ t_30       ┆ _last_prom ┆ _last_holi ┆ ext_holid │
│ u32  ┆ u32      ┆ u32        ┆ ---        ┆   ┆ ---        ┆ o          ┆ day        ┆ ay        │
│      ┆          ┆            ┆ u32        ┆   ┆ u32        ┆ ---        ┆ ---        ┆ ---       │
│      ┆          ┆            ┆            ┆   ┆            ┆ u32        ┆ u32        ┆ u32       │
╞══════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 0    ┆ 0        ┆ 0          ┆ 0          ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0         │
└──────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [47]:
from datetime import date
train_start = date(2016, 10, 18)
train_end = date(2017, 6, 16)
val_start = date(2017, 6, 17)
val_end = date(2017, 7, 16)
test_start = date(2017, 7, 17)
test_end = date(2017, 8, 15)

In [48]:
Master_train = master.filter((pl.col("date") >= train_start) & (pl.col("date") <= train_end))
Master_val = master.filter((pl.col("date") >= val_start) & (pl.col("date") <= val_end))
Master_test = master.filter((pl.col("date") >= test_start) & (pl.col("date") <= test_end))
Master_full_train = master.filter((pl.col("date") >= train_start) & (pl.col("date") <= val_end))

In [49]:
Master_train.null_count()

shape: (1, 61)
┌──────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ date ┆ item_nbr ┆ unit_sales ┆ onpromotio ┆ … ┆ promo_coun ┆ days_since ┆ days_since ┆ days_to_n │
│ ---  ┆ ---      ┆ ---        ┆ n          ┆   ┆ t_30       ┆ _last_prom ┆ _last_holi ┆ ext_holid │
│ u32  ┆ u32      ┆ u32        ┆ ---        ┆   ┆ ---        ┆ o          ┆ day        ┆ ay        │
│      ┆          ┆            ┆ u32        ┆   ┆ u32        ┆ ---        ┆ ---        ┆ ---       │
│      ┆          ┆            ┆            ┆   ┆            ┆ u32        ┆ u32        ┆ u32       │
╞══════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 0    ┆ 0        ┆ 0          ┆ 0          ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0         │
└──────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [50]:
Master_val.null_count()

shape: (1, 61)
┌──────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ date ┆ item_nbr ┆ unit_sales ┆ onpromotio ┆ … ┆ promo_coun ┆ days_since ┆ days_since ┆ days_to_n │
│ ---  ┆ ---      ┆ ---        ┆ n          ┆   ┆ t_30       ┆ _last_prom ┆ _last_holi ┆ ext_holid │
│ u32  ┆ u32      ┆ u32        ┆ ---        ┆   ┆ ---        ┆ o          ┆ day        ┆ ay        │
│      ┆          ┆            ┆ u32        ┆   ┆ u32        ┆ ---        ┆ ---        ┆ ---       │
│      ┆          ┆            ┆            ┆   ┆            ┆ u32        ┆ u32        ┆ u32       │
╞══════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 0    ┆ 0        ┆ 0          ┆ 0          ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0         │
└──────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [51]:
Master_test.null_count()

shape: (1, 61)
┌──────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ date ┆ item_nbr ┆ unit_sales ┆ onpromotio ┆ … ┆ promo_coun ┆ days_since ┆ days_since ┆ days_to_n │
│ ---  ┆ ---      ┆ ---        ┆ n          ┆   ┆ t_30       ┆ _last_prom ┆ _last_holi ┆ ext_holid │
│ u32  ┆ u32      ┆ u32        ┆ ---        ┆   ┆ ---        ┆ o          ┆ day        ┆ ay        │
│      ┆          ┆            ┆ u32        ┆   ┆ u32        ┆ ---        ┆ ---        ┆ ---       │
│      ┆          ┆            ┆            ┆   ┆            ┆ u32        ┆ u32        ┆ u32       │
╞══════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 0    ┆ 0        ┆ 0          ┆ 0          ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0         │
└──────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [52]:
Master_full_train.null_count()

shape: (1, 61)
┌──────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ date ┆ item_nbr ┆ unit_sales ┆ onpromotio ┆ … ┆ promo_coun ┆ days_since ┆ days_since ┆ days_to_n │
│ ---  ┆ ---      ┆ ---        ┆ n          ┆   ┆ t_30       ┆ _last_prom ┆ _last_holi ┆ ext_holid │
│ u32  ┆ u32      ┆ u32        ┆ ---        ┆   ┆ ---        ┆ o          ┆ day        ┆ ay        │
│      ┆          ┆            ┆ u32        ┆   ┆ u32        ┆ ---        ┆ ---        ┆ ---       │
│      ┆          ┆            ┆            ┆   ┆            ┆ u32        ┆ u32        ┆ u32       │
╞══════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 0    ┆ 0        ┆ 0          ┆ 0          ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0         │
└──────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [53]:
len(Master_full_train)

837760

In [54]:
len(Master_train)

745360

In [55]:
len(Master_val)

92400

In [56]:
len(Master_test)

92400

In [57]:
Master_train.write_csv("Store39_Dataset/MasterTrain.csv")
Master_val.write_csv("Store39_Dataset/MasterVal.csv")
Master_test.write_csv("Store39_Dataset/MasterTest.csv")
Master_full_train.write_csv("Store39_Dataset/MasterFullTrain.csv")

In [58]:
Master_train.head(200).write_csv("Store39_Dataset/MasterTrainPreview.csv")

In [59]:
Master_train.filter(pl.col('unit_sales') < 0)

shape: (0, 61)
┌──────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ date ┆ item_nbr ┆ unit_sales ┆ onpromotio ┆ … ┆ promo_coun ┆ days_since ┆ days_since ┆ days_to_n │
│ ---  ┆ ---      ┆ ---        ┆ n          ┆   ┆ t_30       ┆ _last_prom ┆ _last_holi ┆ ext_holid │
│ date ┆ i64      ┆ f64        ┆ ---        ┆   ┆ ---        ┆ o          ┆ day        ┆ ay        │
│      ┆          ┆            ┆ i64        ┆   ┆ i64        ┆ ---        ┆ ---        ┆ ---       │
│      ┆          ┆            ┆            ┆   ┆            ┆ i64        ┆ i64        ┆ i64       │
╞══════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
└──────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘